### PR TITLE
fix Shows gear icon in the controll menu on no button

### PR DESCRIPTION
**Pull request by r22n**
hi :)
I found gear icon appears on controll menu even if it had no button, so I fixed this as issue.

Commits contain some changes;

before
shows gear icon  whenever

after
hides gear icon if no button
otherwise, show

### CODE REVIEW

**Comment by r22n** [comment]
And I have idea for refactoring css smarter.
If you mind please check it !

**Comment by giovanesantossilva** [comment]
Hi, I will check it soon, thank you very much.

**Comment by giovanesantossilva** [comment]
I'll add it together with the new update, thanks a lot!

**Comment by r22n** [comment]
Thank you :)
I wait merging this from closed and thanks new updates for good product

**Comment by r22n** [comment]
When you merge this ?
I will remove branch if you dont need this.

**Pull request closed without merging**
